# Log activation modules 
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=1
CONFIG_LOG_MODE_MINIMAL=y

# Modules used by this app
CONFIG_PWM=y
CONFIG_GPIO=y

# Used to append MCUBoot application image header
CONFIG_BOOTLOADER_MCUBOOT=y
CONFIG_MCUBOOT_GENERATE_UNSIGNED_IMAGE=y
CONFIG_MCUBOOT_BOOTLOADER_MODE_RAM_LOAD=y
