# Log activation modules 
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=1
CONFIG_LOG_MODE_MINIMAL=y

# Modules used by this app
CONFIG_PWM=y
CONFIG_GPIO=y

# Used for MCUBoot application image footer
CONFIG_FLASH=y
CONFIG_STREAM_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_IMG_MANAGER=y
CONFIG_MCUBOOT_IMG_MANAGER=y
CONFIG_SPI_NOR_SFDP_RUNTIME=y

